### ISSUE TITLE
realm.toLowerCase() does not work for all realms

### ISSUE THREAD

**Issue by kenhia** [Blizzard/node-signature-generator#1]
https://github.com/Blizzard/node-signature-generator/blob/d8811908c830ff67970b1dbefe0c54796c02b456/index.js#L120

I went with a similar approach for realmSlug in the PowerShell implementation that I'm working on and discovered it works _almost_ all the time. It fails on realms named with two words like `Steamwheedle Cartel` which must be mapped to `steamwheedle-cartel`.

I ended up going the route of writing a `Get-RealmSlug` function which looks up the slug from the data from `/data/wow/realm/index` but the lowercase and replace spaces with dashes seems to be consistent throughout.

**Comment by kviglucci-blizzard** [comment]
Thanks for the issue kenhia.

This issue is likely resolved with our latest updates to this example application.
